apiVersion: v1
kind: Service
metadata:
  name: bookunit-service
  labels:
    app: bookunit-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app: bookunit-service 