stages:
  - build
  - test
  - deploy

variables:
  # Gradle-specific variables
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Enable Git long paths
  GIT_CONFIG_PARAMETERS: "core.longpaths=true"

# Cache Gradle dependencies to speed up builds
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Clean up Gradle cache after build
after_script:
  - rm -rf bookunit_service/.gradle

build:
  stage: build
  image: gradle:jdk17 # Use the appropriate Gradle and JDK version for your project
  script:
    - cd bookunit_service
    - gradle build
  artifacts:
    paths:
      - bookunit_service/build/libs/*.jar

test:
  stage: test
  image: gradle:jdk17
  script:
    - cd bookunit_service
    - gradle test
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd database
    - docker-compose up -d
    - cd ../bookunit_service
    - docker build -t bookunit_service:latest .
    - docker run -d --name bookunit_service_app --network host bookunit_service:latest
  only:
    - main # Deploy only when changes are pushed to the main branch
