stages:
  - build
  - test
  - deploy

variables:
  # Gradle-specific variables
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Cache Gradle dependencies to speed up builds
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Clean up Gradle cache after build
after_script:
  - rm -rf service/.gradle

build:
  stage: build
  image: gradle:jdk17 # Use the appropriate Gradle and JDK version for your project
  script:
    - git config --global core.longpaths true
    - cd service
    - gradle build
  artifacts:
    paths:
      - service/build/libs/*.jar

test:
  stage: test
  image: gradle:jdk17
  script:
    - git config --global core.longpaths true
    - cd service
    - gradle test
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - git config --global core.longpaths true
    - cd database
    - docker-compose up -d
    - cd ../service
    - docker build -t service:latest .
    - docker run -d --name service_app --network host service:latest
  only:
    - main # Deploy only when changes are pushed to the main branch