version: '3.8'

services:
  db4:
    image: postgres:latest
    container_name: bookunit_container
    environment:
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: db4
    ports:
      - "5435:5432"
    volumes:
      - db4-data:/var/lib/postgresql/data

volumes:
  db4-data: